// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gflow-kratos/app/workflow/internal/biz"
	"gflow-kratos/app/workflow/internal/conf"
	"gflow-kratos/app/workflow/internal/data"
	"gflow-kratos/app/workflow/internal/server"
	"gflow-kratos/app/workflow/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewGormDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	workflowRepo := data.NewWorkflowRepo(dataData, logger)
	workflowUseCase := biz.NewWorkflowUseCase(workflowRepo, logger)
	processRepo := data.NewProcessRepo(dataData, logger)
	processUseCase := biz.NewProcessUseCase(processRepo, logger)
	workflowService := service.NewWorkflowService(workflowUseCase, processUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, workflowService, logger)
	grpcServer := server.NewGRPCServer(confServer, workflowService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
